# Development Configuration for Fact-Checker Bot
# This file contains settings that can be modified without changing code

# Voice Activity Detection Settings
vad:
  # Set to true to bypass VAD and send continuous audio to STT
  # Use this if VAD is not detecting speech properly
  disable: true

  # VAD sensitivity parameters (only used when disable=false)
  # start_secs: How long audio must contain speech before triggering (in seconds)
  # stop_secs: How long silence must persist before ending speech segment (in seconds)
  # min_volume: Minimum volume threshold (0.0 to 1.0)
  start_secs: 0.2
  stop_secs: 0.2
  min_volume: 0.6

# Continuous Audio Processing (only used when vad.disable=true)
continuous_audio:
  # How long to buffer audio before sending to STT (in seconds)
  # Recommended: 2-3 seconds for natural speech segments
  buffer_duration: 2.5

  # Whether to overlap buffers to avoid cutting off words
  # If true, buffers will overlap by 50% (e.g., 2.5s buffer with 1.25s overlap)
  overlap: true

# Speech-to-Text Settings
stt:
  # Groq Whisper model to use
  model: "whisper-large-v3-turbo"

  # Language code (ISO 639-1)
  language: "en"

# Logging Settings
logging:
  # Log level: DEBUG, INFO, WARNING, ERROR
  level: "INFO"

  # Enable detailed transcription logging
  log_transcriptions: true
